-- Run this script once in Supabase SQL Editor.
create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz default now()
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  category_id bigint references categories(id),
  image_url text,
  icon text default '📦',
  is_visible boolean default true,
  sort_order integer default 0,
  created_at timestamptz default now()
);

create table if not exists printing_services (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  icon text default '🖨️',
  is_visible boolean default true,
  sort_order integer default 0,
  created_at timestamptz default now()
);

create table if not exists site_settings (
  id bigint generated by default as identity primary key,
  phone text default '01098090100',
  whatsapp text default '201098090100',
  address text,
  updated_at timestamptz default now()
);

insert into categories (name)
select x.name from (values ('كتب'), ('أدوات مكتبية'), ('مستلزمات مدرسية'), ('خدمات الطباعة')) as x(name)
where not exists (select 1 from categories);

insert into site_settings (phone, whatsapp)
select '01098090100', '201098090100'
where not exists (select 1 from site_settings);

alter table categories enable row level security;
alter table products enable row level security;
alter table printing_services enable row level security;
alter table site_settings enable row level security;

drop policy if exists "public read categories" on categories;
create policy "public read categories" on categories for select to anon, authenticated using (true);

drop policy if exists "public read visible products" on products;
create policy "public read visible products" on products for select to anon, authenticated using (is_visible = true);

drop policy if exists "public read visible services" on printing_services;
create policy "public read visible services" on printing_services for select to anon, authenticated using (is_visible = true);

drop policy if exists "public read site settings" on site_settings;
create policy "public read site settings" on site_settings for select to anon, authenticated using (true);

-- Create a Storage bucket named product-images from Storage in the dashboard.
-- Keep uploads restricted to authenticated admin users in production.
