-- Run this script once in Supabase SQL Editor.
create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz default now()
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  category_id bigint references categories(id),
  image_url text,
  icon text default '📦',
  is_visible boolean default true,
  sort_order integer default 0,
  created_at timestamptz default now()
);

create table if not exists printing_services (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  icon text default '🖨️',
  is_visible boolean default true,
  sort_order integer default 0,
  created_at timestamptz default now()
);

create table if not exists site_settings (
  id bigint generated by default as identity primary key,
  phone text default '01098090100',
  whatsapp text default '201098090100',
  address text,
  updated_at timestamptz default now()
);

insert into categories (name)
select x.name from (values ('كتب'), ('أدوات مكتبية'), ('مستلزمات مدرسية'), ('خدمات الطباعة')) as x(name)
where not exists (select 1 from categories);

insert into site_settings (phone, whatsapp)
select '01098090100', '201098090100'
where not exists (select 1 from site_settings);

alter table categories enable row level security;
alter table products enable row level security;
alter table printing_services enable row level security;
alter table site_settings enable row level security;

drop policy if exists "public read categories" on categories;
create policy "public read categories" on categories for select to anon, authenticated using (true);

drop policy if exists "public read visible products" on products;
create policy "public read visible products" on products for select to anon using (is_visible = true);
drop policy if exists "authenticated read all products" on products;
create policy "authenticated read all products" on products for select to authenticated using (true);
drop policy if exists "authenticated insert products" on products;
create policy "authenticated insert products" on products for insert to authenticated with check (true);
drop policy if exists "authenticated update products" on products;
create policy "authenticated update products" on products for update to authenticated using (true) with check (true);
drop policy if exists "authenticated delete products" on products;
create policy "authenticated delete products" on products for delete to authenticated using (true);

drop policy if exists "public read visible services" on printing_services;
create policy "public read visible services" on printing_services for select to anon, authenticated using (is_visible = true);

drop policy if exists "public read site settings" on site_settings;
create policy "public read site settings" on site_settings for select to anon, authenticated using (true);

-- Hierarchy: section -> product type -> product.
create table if not exists sections (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer default 0,
  is_visible boolean default true,
  created_at timestamptz default now()
);

create table if not exists product_types (
  id bigint generated by default as identity primary key,
  section_id bigint not null references sections(id) on delete cascade,
  name text not null,
  sort_order integer default 0,
  is_visible boolean default true,
  created_at timestamptz default now(),
  unique(section_id, name)
);

alter table products add column if not exists type_id bigint references product_types(id) on delete set null;
alter table sections enable row level security;
alter table product_types enable row level security;

insert into sections (name, sort_order) values
('المكتبة', 1), ('المستلزمات المدرسية', 2), ('الأدوات المكتبية', 3), ('خدمات الطباعة', 4)
on conflict (name) do nothing;

insert into product_types (section_id, name, sort_order)
select s.id, x.name, x.sort_order from sections s cross join
(values ('كتب ومراجع',1), ('كراسات ومذكرات',2), ('أقلام وأدوات كتابة',3), ('طباعة وتجليد',4)) x(name,sort_order)
where not exists (select 1 from product_types t where t.section_id=s.id and t.name=x.name);

drop policy if exists "public read sections" on sections;
create policy "public read sections" on sections for select to anon, authenticated using (is_visible = true);
drop policy if exists "authenticated manage sections" on sections;
create policy "authenticated manage sections" on sections for all to authenticated using (true) with check (true);
drop policy if exists "public read product types" on product_types;
create policy "public read product types" on product_types for select to anon, authenticated using (is_visible = true);
drop policy if exists "authenticated manage product types" on product_types;
create policy "authenticated manage product types" on product_types for all to authenticated using (true) with check (true);

-- Product image bucket and policies.
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

drop policy if exists "public read product images" on storage.objects;
create policy "public read product images" on storage.objects
for select to anon, authenticated
using (bucket_id = 'product-images');

drop policy if exists "authenticated upload product images" on storage.objects;
create policy "authenticated upload product images" on storage.objects
for insert to authenticated
with check (bucket_id = 'product-images');

drop policy if exists "authenticated update product images" on storage.objects;
create policy "authenticated update product images" on storage.objects
for update to authenticated
using (bucket_id = 'product-images') with check (bucket_id = 'product-images');

drop policy if exists "authenticated delete product images" on storage.objects;
create policy "authenticated delete product images" on storage.objects
for delete to authenticated
using (bucket_id = 'product-images');

-- Site appearance and navigation settings.
alter table site_settings add column if not exists hero_image_url text;
alter table site_settings add column if not exists hero_title text default 'كل احتياجاتك المدرسية والمكتبية في مكان واحد';
alter table site_settings add column if not exists hero_description text default 'كتب ومذكرات وأدوات مدرسية وكشاكيل وخدمات طباعة وتصوير.';
alter table site_settings add column if not exists work_hours text;
alter table site_settings add column if not exists nav_items jsonb default '[{"label":"الرئيسية","href":"#"},{"label":"المنتجات","href":"products.html"},{"label":"الكتب والمذكرات","href":"#categories"},{"label":"الأدوات المدرسية","href":"#categories"},{"label":"الطباعة والتصوير","href":"#printing"},{"label":"العروض","href":"#offers"},{"label":"تواصل معنا","href":"#contact"}]'::jsonb;
drop policy if exists "authenticated manage site settings" on site_settings;
create policy "authenticated manage site settings" on site_settings for all to authenticated using (true) with check (true);

insert into site_settings (phone, whatsapp, hero_title, hero_description, work_hours)
select '01098090100', '201098090100', 'كل احتياجاتك المدرسية والمكتبية في مكان واحد', 'كتب ومذكرات وأدوات مدرسية وكشاكيل وخدمات طباعة وتصوير.', 'يوميًا من 9 صباحًا إلى 10 مساءً'
where not exists (select 1 from site_settings);
